### PR TITLE
added Basic Auth for http check

### PR DESCRIPTION
**Pull request by jurijsdmitrijevs**

### CODE REVIEW

**Review by vovanec — COMMENTED** [review]
I noticed you attempted to create pull request, then just cancelled it. I've just added Basic auth for HTTP to my repo anyway. If you have more changes - feel free to submit PR.

**Comment by jurijsdmitrijevs** [comment]
Nice, thanks. Not good in python, so nice to have basic auth implementation from project creator

**Comment by vovanec** [comment]
If you have a chance to play with it, please reply whether it works. I had no chance to test this change yet.

**Comment by jurijsdmitrijevs** [comment]
Sure

**Comment by jurijsdmitrijevs** [comment]
I think need to rewrite this part: https://github.com/vovanec/supervisor_checks/blob/master/supervisor_checks/check_runner.py#L54
Situation what I have now:
1. supervisord.conf
[eventlistener:health_check]
command=/usr/bin/supervisor_http_check -g play_app -n health_check -u /ping -t 30 -r 3 -p %(ENV_HTTP_PORT)s -U user -P 123
events=TICK_60
stderr_logfile=/opt/docker/supervisor_healt_check-stderr.log
stdout_logfile=/opt/docker/supervisor_healt_check-stdout.log
environment=SUPERVISOR_USERNAME=user,SUPERVISOR_PASSWORD=123

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[inet_http_server]
port=9001
username=user
password=123

As you can see I have 3 places where I should define username and password to be able to run http check. So my thought is that check should somehow use inet_http_server or unix_http_server username and password to avoid username an password duplication:
1. To run check I should provide -U and -P <- this needed, because of http_request
2. To run server I should provide username and password <- this needed, to be able to access web ui
3. To run check on TICK Event I should add environment variables <- this neede, because of childutils.getRPCInterface
I think somehow need to get inet or unix username and password and use them everywhere

Maybe I don't know all the stuff and it's a my configuration problem

**Comment by jurijsdmitrijevs** [comment]
Checked http_check from master and seems works as expected with my above config.

**Comment by jurijsdmitrijevs** [comment]
from sources:
def getRPCInterface(env):
return xmlrpclib.ServerProxy('http://127.0.0.1', getRPCTransport(env))

def getRPCTransport(env):
u = env.get('SUPERVISOR_USERNAME', '')
p = env.get('SUPERVISOR_PASSWORD', '')
return SupervisorTransport(u, p, env['SUPERVISOR_SERVER_URL'])

So I think we can set this environment variables ourselves which will remove necessity to add environment variables about which no one knows

**Comment by jurijsdmitrijevs** [comment]
Summary:
It was my bad, I think no need in basic auth in http_check, need a basic auth possibility without providing environment variables (SUPERVISOR_USERNAME,SUPERVISOR_PASSWORD,SUPERVISOR_SERVER_URL). Need somehow extract this values from supervisord configs

**Comment by vovanec** [comment]
Sorry, I don’t see the relation between health check event listener and inet_http_server which is internal supervisor thing used to control itself.

HTTP check(and all supervisor checks in general) designed to monitor and control external programs, e.g. some web service you’re running under supervisor. Very common practice is to provide locally accessible HTTP/RPC methods usually called ping or health_check which collects overall program status and return it back to the caller(health check in our case). Often those status methods do not use authorization as they are only accessible from localhost. That’s why I had no authorization in the initial implementation.

That said:

1. Username/password you optionally have to set as supervisor_http_check parameter are credentials to access /ping method in play_app you’ve built yourself.
2. environment variable is just to pass the environment to the even listener itself. I’m not sure you need it, maybe you need it so event listener is able to talk to supervisor? In this case this should be XML RPC credentials of supervisor itself, not your play_app.
3. inet_http_server - as I understand this is only related to user Web UI, and not directly related to the program you want to monitor.

Please let me know if you have more questions.

thanks,
—Vovan

**Comment by vovanec** [comment]
I am not sure event listeners have an access to other supervisor configuration except its own section. Anyway, if you have something - please submit a pull request. 

Note, the right piece of code to change is in check_runner.py itself, not in xmlrpc_check.py(this check is to query health status of the external program via XML RPC):

def _restart_process(self, process_spec):
    """Restart a process.
    """

    name_spec = make_namespec(
        process_spec[GROUP_KEY], process_spec[NAME_KEY])

    rpc_client = childutils.getRPCInterface(self._environment) # here environment is passed, I suspect we can set username/password here(assuming we can extract and get them :)

thanks
—Vovan

**Comment by vovanec** [comment]
If you password protect your /ping method in play_app - will http check work then?

**Comment by jurijsdmitrijevs** [comment]
> If you password protect your /ping method in play_app - will http check work then?

Yes, I checked that

> environment variable is just to pass the environment to the even listener itself. I’m not sure you need it, maybe you need it so event listener is able to talk to supervisor? In this case this should be XML RPC credentials of supervisor itself, not your play_app.

Yes, they are needed to be able to talk with supervisor if I use inet_http_sever or unix_http_server with username and password. Without them http check will fail with 401 Unauthorized error

**Comment by jurijsdmitrijevs** [comment]
Everything is good, no additional pull request from me. I just incorrectly understood the whole xml rpc stuff =)

**Comment by vovanec** [comment]
Sorry, I don’t see the relation between health check event listener and
*inet_http_server* which is internal supervisor thing used to control
itself.

HTTP check(and all supervisor checks in general) designed to monitor and
control *external* programs, e.g. some web service you’re running under
supervisor. Very common practice is to provide locally accessible HTTP/RPC
methods usually called ping or health_check which collects overall program
status and return it back to the caller(health check in our case). Often
those status methods do not use authorization as they are only accessible
from localhost. That’s why I had no authorization in the initial
implementation.

That said:

1. Username/password you optionally have to set as supervisor_http_check
parameter *are credentials to access /ping method in play_app you’ve built
yourself*.
2. *environment* variable is just to pass the environment to the even
listener itself. I’m not sure you need it, maybe you need it so event
listener is able to talk to supervisor? In this case this should be XML RPC
credentials of supervisor itself, not your *play_app*.
3. *inet_http_server - *as I understand this is only related to user Web
UI, and not directly related to the program you want to monitor.

Please let me know if you have more questions.

thanks,
—Vovan

On Feb 1, 2017, at 12:25 AM, jurijsdmitrijevs <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

I think need to rewrite this part: https://github.com/vovanec/
supervisor_checks/blob/master/supervisor_checks/check_runner.py#L54
Situation what I have now:

   1. supervisord.conf
   [eventlistener:health_check]
   command=/usr/bin/supervisor_http_check -g play_app -n health_check -u
   /ping -t 30 -r 3 -p %(ENV_HTTP_PORT)s -U user -P 123
   events=TICK_60
   stderr_logfile=/opt/docker/supervisor_healt_check-stderr.log
   stdout_logfile=/opt/docker/supervisor_healt_check-stdout.log
   environment=SUPERVISOR_USERNAME=admin,SUPERVISOR_PASSWORD=DrU8acra

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_
rpcinterface

[inet_http_server]
port=9001
username=user
password=123

As you can see I have 3 places where I should define username and password
to be able to run http check. So my thought is that check should somehow
use inet_http_server or unix_http_server username and password to avoid
username an password duplication:

   1. To run check I should provide -U and -P
   2. To run server I should provide username and password
   3. To run check on TICK Event I should add environment variables
   I think somehow need to get inet or unix username and password and use
   them everywhere

Maybe I don't know all the stuff and it's a my configuration problem

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/vovanec/supervisor_checks/pull/2#issuecomment-276599208>,
or mute the thread

**Comment by vovanec** [comment]
Oh, nice. Thanks for the confirmation and testing it.
—Vovan

**Pull request closed without merging**
